name: Playwright E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_openasp
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Node dependencies (root)
      run: npm ci

    - name: Install Playwright Browsers
      run: |
        export PLAYWRIGHT_BROWSERS_PATH=$HOME/.cache/ms-playwright
        npx playwright install chromium
        npx playwright install-deps chromium

    - name: Verify browser installation
      run: |
        ls -la $HOME/.cache/ms-playwright/
        find $HOME/.cache/ms-playwright/ -name "*chrome*" -type f || true
      env:
        PLAYWRIGHT_BROWSERS_PATH: $HOME/.cache/ms-playwright

    - name: Install Node dependencies (asp-manager)
      working-directory: ./asp-manager
      run: npm ci

    - name: Install Node dependencies (ofasp-refactor)
      working-directory: ./ofasp-refactor
      run: npm ci

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ofasp-refactor/server/requirements.txt
        pip install flask flask-cors requests psycopg2-binary pytest

    - name: Create test environment file
      run: |
        echo "NODE_ENV=test" > .env
        echo "CI=true" >> .env
        echo "FLASK_ENV=testing" >> .env
        echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_openasp" >> .env

    - name: Wait for PostgreSQL
      run: |
        for i in {1..30}; do
          pg_isready -h localhost -p 5432 -U postgres && break
          echo "Waiting for PostgreSQL..."
          sleep 1
        done

    - name: Initialize database
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d test_openasp -f database/catalog_schema.sql
        PGPASSWORD=postgres psql -h localhost -U postgres -d test_openasp -f database/create_asp_terminal_table.sql
        PGPASSWORD=postgres psql -h localhost -U postgres -d test_openasp -f database/create_jobinfo_table.sql
      env:
        PGPASSWORD: postgres

    - name: Start backend services
      run: |
        cd server && python api_server.py &
        cd ofasp-refactor/server && python chat_api.py &
        sleep 10
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_openasp

    - name: Run Playwright tests - ${{ matrix.browser }}
      run: npx playwright test --project=${{ matrix.browser }}
      env:
        CI: true
        PLAYWRIGHT_BROWSERS_PATH: $HOME/.cache/ms-playwright

    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.browser }}
        path: |
          playwright-report/
          test-results/

  test-all-browsers:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: All browser tests completed
      run: echo "All Playwright tests passed successfully!"